FITBIT_CONSUMER_KEY = 'YOUR_FITBIT_CONSUMER_KEY'
FITBIT_CONSUMER_SECRET = 'YOUR_FITBIT_CONSUMER_SECRET'
FITBIT_ACCESS_KEY = 'YOUR_FITBIT_ACCESS_KEY'
FITBIT_ACCESS_SECRET = 'YOUR_FITBIT_ACCESS_TOKEN'

# use gmail as our smtp relay
# note: if you use two-step verification
# you must get an application-specific password
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "YOUR_GMAIL_USERNAME"
SMTP_PASSWORD = "YOUR_GMAIL_PASSWORD"

# https://github.com/maximebf/python-withings/
WITHINGS_CONSUMER_KEY = 'YOUR_WITHINGS_CONSUMER_KEY'
WITHINGS_CONSUMER_SECRET = 'YOUR_WITHINGS_CONSUMER_SECRET'
WITHINGS_ACCESS_KEY = 'YOUR_WITHINGS_ACCESS_KEY'
WITHINGS_ACCESS_SECRET = 'YOUR_WITHINGS_ACCESS_SECRET'

FOURSQUARE_CLIENT_ID = 'YOUR_FOURSQUARE_CLIENT_ID'
FOURSQUARE_CLIENT_SECRET = 'YOUR_FOURSQUARE_CLIENT_SECRET'
FOURSQUARE_ACCESS_TOKEN = 'YOUR_FOURSQUARE_ACCESS_TOKEN'
