FITBIT_CONSUMER_KEY = 'YOUR_FITBIT_CONSUMER_KEY'
FITBIT_CONSUMER_SECRET = 'YOUR_FITBIT_CONSUMER_SECRET'
FITBIT_ACCESS_KEY = 'YOUR_FITBIT_ACCESS_KEY'
FITBIT_ACCESS_SECRET = 'YOUR_FITBIT_ACCESS_TOKEN'

# use gmail as our smtp relay
# note: if you use two-step verification
# you must get an application-specific password
SMTP_SERVER = "smtp.gmail.com"
SMTP_PORT = 587
SMTP_USERNAME = "YOUR_GMAIL_USERNAME"
SMTP_PASSWORD = "YOUR_GMAIL_PASSWORD"